In [1]:
import numpy as np
import pyautogui as pg
import time
import math

In [3]:

# Create empty list to be filled with the sudoku rows
grid = []

# Insert the 9 rows
def Create():

    """ This function is needed to get the Sudoku input by rows.
        The input required is every number of each row one by one, without commas.
        Example: 027390030 (then click enter and proceed with the following row). """

    while True:
        row = list(input('Please input the whole row of numbers without commas: '))
    
        if len(row) != 9: # Do not append the input if the lenght is not equal to 9
            print('You need to type 9 numbers!')
        else:
            ints = [] 

            [ints.append(int(n)) for n in row] # Separate the numbers and convert it to integer

            grid.append(ints) # Attach the list to the Sudoku "matrix" (actually is a list)

            if len(grid) == 9: # Close the loop when the "matrix" has 9 rows
                #print('Row ' + str(len(grid)) + ' complete')
                break
            #print('Row ' + str(len(grid)) + ' complete')

    time.sleep(3) # To give us some time to switch to the Sudoku after running the script




def Possible(y,x,n):

    """ Define a function that checks wheter that number (n) can fit into that (x,y) spot
    n = number from 1 to 9
    x = spot of the number in the row
    y = spot of the number in the column """

    global grid
    # Check the row
    for i in range(0,9): # row position is fixed [y] and [i] changes
        if grid[y][i]==n: 
            return False
    
    # Check the column
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    
    # Check the box
    x0= (x//3)*3 # Return x location of the leftmost item in that box
    y0= (y//3)*3 # Return y location of the upper item in that box
        # Basically the code above brings every x,y coordinates you ingest to the upperleft location of the box where x,y are located

    for i in range(3): # 3 columns in the box
        for j in range(3): # 3 rows in the box
            if grid[y0+i][x0+j] == n:
                return False
    
    return True



def Print(matrix):

    # Reverse the solution of the Sudoku
    reversed_matrix = []

    for i, list in enumerate(matrix):
        if i%2 == 0:
            reversed_matrix.append(list)
        else:
            reversed_matrix.append(list[::-1])


    # Create string version of the matrix
    str_fin = []

    for lists in reversed_matrix:
        for num in lists:
            str_fin.append(str(num))
    

    # Put the numbers into the Sudoku
    counter = 0

    for i, num in enumerate(str_fin):
        
        if (math.floor(i/9))%2 == 0:
            print((math.floor(i/9))%2)
            print('Counter: ',counter)
            print(num,'right')
            pg.press(num) # Press the key num (passing the string)
            pg.hotkey('right')
            counter += 1
        
        elif (math.floor(i/9))%2 != 0:
            print((math.floor(i/9))%2)
            print('Counter: ',counter)
            print(num,'left')
            pg.press(num) # Press the key num (passing the string)
            pg.hotkey('left')
            counter += 1

        if (counter%9 == 0) and (counter != 81):
            print((math.floor(i/9))%2)
            print('Counter: ',counter)
            print('down')
            pg.hotkey('down')

def Solve():
    global grid
    for y in range(9): # to iterate through rows
        for x in range(9): # to iterate trough columns
            if grid[y][x] == 0: # If the spot is empy in the grid
                for n in range(1,10):
                    if Possible(y,x,n): # Check using the possible function which number can we put there
                        grid[y][x] = n
                        solve() # Backtracking if the choice made was wrong
                        grid[y][x] = 0 # Change latest grid created but we turn back the n to zero
                return # When there are no more empty spots left
    print('Solving...')
    print(np.matrix(grid))
    time.sleep(3)
    Print(grid)
    input('Do you want to see more solutions?')


Create() # Run the function to create the Sudoku

Solve() # Solve it


Solving...
[[2 4 7 5 6 8 9 3 1]
 [1 9 5 3 4 2 6 7 8]
 [8 6 3 1 9 7 2 4 5]
 [4 3 9 8 5 1 7 6 2]
 [7 8 1 9 2 6 3 5 4]
 [5 2 6 4 7 3 8 1 9]
 [3 1 2 6 8 5 4 9 7]
 [6 7 4 2 1 9 5 8 3]
 [9 5 8 7 3 4 1 2 6]]
0
Counter:  0
2 right
0
Counter:  1
4 right
0
Counter:  2
7 right
0
Counter:  3
5 right
0
Counter:  4
6 right
0
Counter:  5
8 right
0
Counter:  6
9 right
0
Counter:  7
3 right
0
Counter:  8
1 right
0
Counter:  9
down
1
Counter:  9
8 left
1
Counter:  10
7 left
1
Counter:  11
6 left
1
Counter:  12
2 left
1
Counter:  13
4 left
1
Counter:  14
3 left
1
Counter:  15
5 left
1
Counter:  16
9 left
1
Counter:  17
1 left
1
Counter:  18
down
0
Counter:  18
8 right
0
Counter:  19
6 right
0
Counter:  20
3 right
0
Counter:  21
1 right
0
Counter:  22
9 right
0
Counter:  23
7 right
0
Counter:  24
2 right
0
Counter:  25
4 right
0
Counter:  26
5 right
0
Counter:  27
down
1
Counter:  27
2 left
1
Counter:  28
6 left
1
Counter:  29
7 left
1
Counter:  30
1 left
1
Counter:  31
5 left
1
Counter:  32
8 left
1
Coun

In [31]:
""" Define a function that checks wheter that number (n) can fit into that (x,y) spot
n = number from 1 to 9
x = spot of the number in the row
y = spot of the number in the column """

def possible(y,x,n):
    global grid
    # Check the row
    for i in range(0,9): # row position is fixed [y] and [i] changes
        if grid[y][i]==n: 
            return False
    
    # Check the column
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    
    # Check the box
    x0= (x//3)*3 # Return x location of the leftmost item in that box
    y0= (y//3)*3 # Return y location of the upper item in that box
        # Basically the code above brings every x,y coordinates you ingest to the upperleft location of the box where x,y are located

    for i in range(3): # 3 columns in the box
        for j in range(3): # 3 rows in the box
            if grid[y0+i][x0+j] == n:
                return False
    
    return True


In [24]:
def Print(matrix):
    final = []
    str_fin = []
    for i in range(9):
        final.append(matrix[i])
    
    # Create string version of the matrix
    for lists in final:
        for num in lists:
            str_fin.append(str(num))
    
    counter = 0

    for num in str_fin:
        if counter%9 == 0:
            pg.hotkey('down')
        
        if round(counter/9,0)%2 == 0:
            pg.press(num) # Press the key num (passing the string)
            pg.hotkey('right')
            counter += 1
        
        if round(counter/9,0)%2 != 0:
            pg.press(num) # Press the key num (passing the string)
            pg.hotkey('left')
            counter += 1
        
    

In [34]:
def solve():
    global grid
    for y in range(9): # to iterate through rows
        for x in range(9): # to iterate trough columns
            if grid[y][x] == 0: # If the spot is empy in the grid
                for n in range(1,10):
                    if possible(y,x,n): # Check using the possible function which number can we put there
                        grid[y][x] = n
                        solve() # Backtracking if the choice made was wrong
                        grid[y][x] = 0 # Change latest grid created but we turn back the n to zero
                return # When there are no more empty spots left
    Print(grid)
    input('Do you want to see more solutions?')

In [35]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
